name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: ./mvnw clean install -DskipTests

      - name: Autenticar no DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/transito-app:latest .

      - name: Push da imagem para o DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/transito-app:latest
